# Site settings
title: Kunal Gaba
email: kunalgaba@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing my thoughts on technology (AEM, digital marketing and Java).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kunalgaba.github.io" # the base hostname & protocol for your site
twitter_username: kunalgaba
github_username:  kunalgaba

# Build settings
markdown: kramdown
